server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Karan@123mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  #  application:
#    name: USER-SERVICE

#spring.config.import= configserver:http://localhost:8085
  config:
    import: optional:configserver:http://localhost:8085


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/
#          jwk-set-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/.well-known/jwks.json

      client:
        registration:
          auth0-client:
            provider: auth0
            authorization-grant-type: client_credentials
            client-id: JnAYktZ1MWZNJL8URZg6AmQIoE05911D
            client-secret: HPc5SLaw_DCgecDQANAFrINGf6YveDqKH6wutf1zJ6mbrYh3RhLmZdk-izoR0gxW
          scope:
              - openid
              - profile
              - email

        provider:
          auth0:
            issuer-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/


#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/
#      client:
#        registration:
#          my-internal-client:
#            provider: okta
#            authorization-grant-type: client-credentials
#            scope: internal
#            client-id: JnAYktZ1MWZNJL8URZg6AmQIoE05911D
#            client-secret: HPc5SLaw_DCgecDQANAFrINGf6YveDqKH6wutf1zJ6mbrYh3RhLmZdk-izoR0gxW
#            scopes: openid, profile, email, offline_access
#        provider:
#          okta:
#            issuer-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/



#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/
#
#      client:
#        registration:
#          auth0-client:
#            provider: auth0
#            authorization-grant-type: client_credentials
#            client-id: JnAYktZ1MWZNJL8URZg6AmQIoE05911D
#            client-secret: HPc5SLaw_DCgecDQANAFrINGf6YveDqKH6wutf1zJ6mbrYh3RhLmZdk-izoR0gxW
#          scope:
#            - openid
#            - profile
#            - email
#
#        provider:
#          auth0:
#            issuer-uri: https://dev-ew3corgfi2z0hauo.us.auth0.com/
#
#
#okta:
#  oauth2:
#    issuer: https://dev-ew3corgfi2z0hauo.us.auth0.com/
#    audience: api://default

#  profiles:
#    active: prod


#Geting this config details from config server
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka



#handling the breaking service
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      ratingHotelService:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 2s



